= Guided solution (page 1 of 2)
:experimental:

== Objectives

* Investigate why the minor upgrade to 6.15.z is failing in Red Hat Satellite 6.
* Solve the upgrade issue in the hands-on lab environment.

== Instructions

Run following instructions on `satellite` system with `root` as user.

.Sample output:
----
[ec2-user@satellite ~]$ sudo su -
[root@satellite ~]#
----

* ISSUE 1: Try to enable the maintenance repo using:
+
[source,bash,role=execute]
----
subscription-manager repos --enable satellite-maintenance-6.15-for-rhel-8-x86_64-rpms
----
but if fails:
+
.Sample output:
----
Error: 'satellite-maintenance-6.15-for-rhel-8-x86_64-rpms' does not match a valid repository ID. Use "subscription-manager repos --list" to see valid repositories.
----
+
This is because the satellite is registered to some other satellite/capsule server. Follow the below steps to fix it
 

Remove the existing katello-ca-consumer
[source,bash,role=execute]
----
rpm -qa | grep katello-ca-consumer | xargs rpm -e
----
Unregister the satellite
[source,bash,role=execute]
----
subscription-manager clean
---- 
Rename or move the rhsm.conf 
[source,bash,role=execute]
----
mv /etc/rhsm/rhsm.conf /var/tmp
----
Create a fresh rhsm.conf which points to the CDN
[source,bash,role=execute]
----
cp /etc/rhsm/rhsm.conf.kat-backup /etc/rhsm/rhsm.conf`
----
Register it to the Red Hat Portal using your own credentials
[source,bash,role=execute]
----
subscription-manager register
----
Also make sure manage_repos has 1 instead of 0 in /etc/rhsm/rhsm.conf and then
[source,bash,role=execute]
----
subscription-manager refresh
----
Now enable the required repos and the required module using:
[source,bash,role=execute]
----
subscription-manager repos --enable=rhel-8-for-x86_64-baseos-rpms \
--enable=rhel-8-for-x86_64-appstream-rpms \
--enable=satellite-6.15-for-rhel-8-x86_64-rpms \
--enable=satellite-maintenance-6.15-for-rhel-8-x86_64-rpms
----
Enable the required module
[source,bash,role=execute]
----
dnf module enable satellite:el8
----

* ISSUE 2: Run
+
[source,bash,role=execute]
----
satellite-maintain upgrade check --target-version 6.15
----
but if fails with:
+
.Sample output:

----
Setup hammer: 
Configuring Hammer CLI...
Hammer admin password: 
                                                                      [FAIL]
Hammer configuration failed: Incorrect credential for admin user.
--------------------------------------------------------------------------------
----

To debug further run:
[source,bash,role=execute]
----
hammer ping
----
It shows

.Sample output:
----
Error: Failed to open TCP connection to satellite.xxxx.sandboxxxxx.opentlc.com:443 (No route to host - connect(2) for "satellite.xxxx.sandboxxxxx.opentlc.com" port 443)
----

This is because the ip in /etc/hosts is incorrect. Check the ip using the below command and correct it in `/etc/hosts` in the satellite for the satellite hostname entry.
[source,bash,role=execute]
----
ip a s
----

* ISSUE 3: Now run:

[source,bash,role=execute]
----
satellite-maintain upgrade check --target-version 6.15
----
but if fails with:

.Sample output:
----
Check whether all services are running using the ping call:           [FAIL]
Couldn't connect to the server: SSL_connect returned=1 errno=0 state=error: certificate verify failed (Hostname mismatch)
----

This is because the fqdn [hostname -f] on satellite is incorrectly set as shortname. Check for the actual fqdn in the details for this lab or in `/etc/hosts` on the line where we corrected ip in the previois step and update it via
----
hostnamectl set-hostname <actual satellite-fqdn>`
----

* ISSUE 4: Now again run:
+
[source,bash,role=execute]
----
satellite-maintain upgrade check --target-version 6.15
----
but it fails with:

.Sample output:
----
Check if system requirements match current tuning profile:            [FAIL] 

ERROR: The installer is configured to use the large tuning profile and does not meet the requirements. 
The number of CPU cores for the system is 8 but the currently configured tuning profile requires 16. 
----

This is because incorrect tuning profile set so edit `/etc/foreman-installer/scenarios.d/satellite.yaml` and set `tuning profile` as `medium` or `default` in place of large

Now again run:

[source,bash,role=execute]
----
satellite-maintain upgrade check --target-version 6.15
----
This should complete successfully now.

* ISSUE 5: Now run the actual upgrade using the below command and provide `yes` to any questions asked for continuing the upgrade.

[source,bash,role=execute]
----
satellite-maintain upgrade run --target-version 6.15
----
but it fails with:

.Sample output:
----
[ERROR ] [configure] Could not prefetch yumrepo provider 'inifile': Section "rhel-8-for-x86_64-baseos-rpms" is already defined, cannot redefine (file: /etc/yum.repos.d/redhat.repo) +
----

This is because /etc/yum.repos.d/rh-cloud.repo.repo file having duplicate or incorrect entries. Remove the /etc/yum.repos.d/rh-cloud.repo file.

[source,bash,role=execute]
----
rm -rf /etc/yum.repos.d/rh-cloud.repo
----

Now run the upgrade and it should complete successully
[source,bash,role=execute]
----
satellite-maintain upgrade run --target-version 6.15
----

.Sample output:
----
2025-02-11 07:59:28 [NOTICE] [configure] System configuration has finished.
  Success!
  * Satellite is running at https://satellite.xxx.yyy
----