= What’s in this break-fix?

== In this break-fix:

**Type of issue:**

The provided Satellite 6.15.4 server needs a minor upgrade to 6.15.z. But its failing due to some incorrect configurations. Fix the encountered errors and ensure a successful upgrade to 6.15.z.


**What you should already know:**

- This training assumes that you are a Red Hat Certified System Administrator (RHCSA) or have equivalent experience administrating Red Hat Enterprise Linux 7 or 8. +
- Administering Red Hat Satellite 6 .


**How break-fix training works:**

. Challenge yourself in the break-fix activity. It describes a problem scenario that's simulated in the lab environment where you can investigate and solve the problem.
. Follow up with the guided solution:
.. If you weren't able to solve the problem on your own, read and follow the instructions in the Guided Solution to complete this training.
.. If you were successful in solving the problem, read the solution for useful tips you can apply when solving similar problems.